# Generated by Django 5.2.13 on 2026-09-09 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_budget_user_expense_user_goal_user_income_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
    ]
