# Generated by Django 5.2.13 on 2026-09-10 16:10

from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_expense_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='user',
            field=django.db.models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='auth.user',
            ),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=django.db.models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='auth.user',
            ),
        ),
        migrations.AlterField(
            model_name='budget',
            name='user',
            field=django.db.models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='auth.user',
            ),
        ),
        migrations.AlterField(
            model_name='goal',
            name='user',
            field=django.db.models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='auth.user',
            ),
        ),
        migrations.AlterField(
            model_name='savings',
            name='user',
            field=django.db.models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='auth.user',
            ),
        ),
    ]